generic-service:
  nameOverride: hmpps-dps-reconciliation
  productId: "DPS072" # productId for the product that this belongs to, see README.md for details

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-dps-reconciliation
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-dps-reconciliation-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  namespace_secrets:
    hmpps-dps-reconciliation-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-dps-reconciliation-queue:
      HMPPS_SQS_QUEUES_RECONCILIATION_QUEUE_NAME: "sqs_name"
    rds-database:
      SPRING_FLYWAY_USER: "database_username"
      SPRING_FLYWAY_PASSWORD: "database_password"
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-dps-reconciliation
