apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-detect-non-matches
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cron.detect_non_matches_schedule }}"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          containers:
            - name: detect-non-matches
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              volumeMounts:
                - name: cronjob-api-helpers
                  mountPath: /bin/cronjob-api-helpers.sh
                  readOnly: true
                  subPath: cronjob-api-helpers.sh
              args:
                - /bin/sh
                - -c
                - |
                  #!/bin/bash
                  set -eu

                  . /bin/cronjob-api-helpers.sh

                  AUTH_BASE_URL="{{ index .Values "generic-service" "env" "HMPPS_AUTH_URL" }}"

                  # Main execution
                  TOKEN=$(get_auth_token "$AUTH_BASE_URL" "$CRONJOB_CLIENT_ID" "$CRONJOB_CLIENT_SECRET")
                  echo "Access token retrieved from HMPPS Auth"

                  call_api GET "http://hmpps-dps-reconciliation/reconciliation/detect" "$TOKEN"
                  echo "Completed successfully"
              securityContext:
                capabilities:
                  drop:
                  - ALL
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
              envFrom:
                - secretRef:
                    name: hmpps-prisoner-to-nomis-update
          restartPolicy: Never
          volumes:
            - name: cronjob-api-helpers
              configMap:
                name: cronjob-api-helpers-script
                defaultMode: 0755
