---
# Per environment values which override defaults in hmpps-dps-reconciliation/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: dps-reconciliation-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    PRISON_API_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"

  scheduledDowntime:
    enabled: true
    startup: '50 6 * * 1-5'
    shutdown: '0 18 * * 1-5' # UTC

  # The name has max length of 27 chars (Cronjob name max length is 52 chars, including prefix "hmpps-dps-reconciliation-")
  # The type must exist in enum BatchType
  batchjobs:
    - name: detect-non-matches-new
      type: DETECT_NON_MATCHES
      schedule: "0 8-16/2 * * 1-5"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-nonprod
  rdsAlertsDatabases:
    cloud-platform-ecaa06ca3b89ae46: "DPS reconcilation"
  sqsNumberAlertQueueNames:
    - "syscon-devs-preprod-hmpps_dps_reconciliation_dl_queue"

cron:
  retry_dlqs_schedule: "*/10 8-17 * * 1-5" # UTC
  # SDIT-2804 Running the new batch job in preprod as a test, so "turning off" the old cronjob to prevent interference
  housekeeping_schedule: "0 0 0 31 2"
