---
# Per environment values which override defaults in hmpps-dps-reconciliation/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: dps-reconciliation-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    PRISON_API_URL: "https://prison-api-dev.prison.service.justice.gov.uk"

  scheduledDowntime:
    enabled: true
    startup: '50 6 * * 1-5'
    shutdown: '0 18 * * 1-5' # UTC

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-nonprod
  rdsAlertsDatabases:
    cloud-platform-1b38ce7c35b6c33c: "DPS reconcilation"
  sqsNumberAlertQueueNames:
    - "syscon-devs-dev-hmpps_dps_reconciliation_dl_queue"

cron:
  retry_dlqs_schedule: "*/10 8-17 * * 1-5" # UTC
