alter table MATCHING_EVENT_PAIR ALTER COLUMN DOMAIN_TIME type TIMESTAMP;
alter table MATCHING_EVENT_PAIR ALTER COLUMN OFFENDER_TIME type TIMESTAMP;
alter table MATCHING_EVENT_PAIR ALTER COLUMN PREVIOUS_OFFENDER_TIME type TIMESTAMP;
alter table MATCHING_EVENT_PAIR ALTER COLUMN CREATED_DATE type TIMESTAMP;
